 2021-09-23 00:00:57.951 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No se pudo encontrar el archivoC:\Users\AdminCMC\Downloads\Clientes2.txt
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes2.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileReader.<init>(Unknown Source) ~[?:1.8.0_151]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:26) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
 2021-09-23 00:04:34.693 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No se pudo encontrar el archivoC:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes2.txt
java.io.FileNotFoundException: C:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes2.txt (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileReader.<init>(Unknown Source) ~[?:1.8.0_151]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:26) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
 2021-09-23 00:05:56.045 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No se pudo encontrar el archivoC:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes2.txt
java.io.FileNotFoundException: C:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes2.txt (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileReader.<init>(Unknown Source) ~[?:1.8.0_151]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:26) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestClientesDuplicados.testLeer(TestClientesDuplicados.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
 2021-09-23 00:07:33.504 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No se pudo encontrar el archivoC:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes3.txt
java.io.FileNotFoundException: C:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes3.txt (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileReader.<init>(Unknown Source) ~[?:1.8.0_151]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:26) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
 2021-09-23 00:10:54.435 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No se pudo encontrar el archivoC:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes3.txt
java.io.FileNotFoundException: C:\Users\usuario\Downloads\EclipseNeon\eclipseNeon\WorkSpace\Evaluación java fase 2\Clientes3.txt (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.io.FileReader.<init>(Unknown Source) ~[?:1.8.0_151]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:26) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
 2021-09-24 21:31:31.883 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - Error al armar el cliente en la linea: 0912313123,Beatriz Rosales
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:70) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:30) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
